spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event_manager_db
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
