spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: fn72039@g.fmi.uni-sofia.bg
    password: gbogupithwapixbn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

server:
  port: 8079

