spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin123
    hikari:
      schema: event_manager
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  flyway:
    enabled: true
    locations: /db.migrations

server:
  port: 8079